inherit_from: .rubocop_todo.yml

require:
  - rubocop-rails

AllCops:
  Exclude:
  - 'vendor/**/*'
  - 'db/**/*'
  - 'bin/**/*'
  - 'spec/**/*'
  - 'node_modules/**/*'
  - 'app/channels/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

MethodLength:
  CountComments: false
  Max: 20

Style/Documentation:
  Enabled: false

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
